[project]
name = "image-generation-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.59.0",
    "jupyter>=1.1.1",
    "openai>=2.15.0",
    "python-dotenv>=1.2.1",
]
